// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion   string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ServerTimeUnix int64                  `protobuf:"varint,2,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PingReply) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type StatusReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NginxRunning   bool                   `protobuf:"varint,1,opt,name=nginx_running,json=nginxRunning,proto3" json:"nginx_running,omitempty"`
	NginxVersion   string                 `protobuf:"bytes,2,opt,name=nginx_version,json=nginxVersion,proto3" json:"nginx_version,omitempty"`
	MasterPid      int32                  `protobuf:"varint,3,opt,name=master_pid,json=masterPid,proto3" json:"master_pid,omitempty"`
	ConfigRoot     string                 `protobuf:"bytes,4,opt,name=config_root,json=configRoot,proto3" json:"config_root,omitempty"`
	LastTestOk     bool                   `protobuf:"varint,5,opt,name=last_test_ok,json=lastTestOk,proto3" json:"last_test_ok,omitempty"`
	LastTestOutput string                 `protobuf:"bytes,6,opt,name=last_test_output,json=lastTestOutput,proto3" json:"last_test_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReply) GetNginxRunning() bool {
	if x != nil {
		return x.NginxRunning
	}
	return false
}

func (x *StatusReply) GetNginxVersion() string {
	if x != nil {
		return x.NginxVersion
	}
	return ""
}

func (x *StatusReply) GetMasterPid() int32 {
	if x != nil {
		return x.MasterPid
	}
	return 0
}

func (x *StatusReply) GetConfigRoot() string {
	if x != nil {
		return x.ConfigRoot
	}
	return ""
}

func (x *StatusReply) GetLastTestOk() bool {
	if x != nil {
		return x.LastTestOk
	}
	return false
}

func (x *StatusReply) GetLastTestOutput() string {
	if x != nil {
		return x.LastTestOutput
	}
	return ""
}

// 单个被发现的配置文件
type ConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"` // 相对 config_root 的逻辑路径，如 conf.d/site.conf
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MtimeUnix     int64                  `protobuf:"varint,3,opt,name=mtime_unix,json=mtimeUnix,proto3" json:"mtime_unix,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"` // sha256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFile) Reset() {
	*x = ConfigFile{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFile) ProtoMessage() {}

func (x *ConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFile.ProtoReflect.Descriptor instead.
func (*ConfigFile) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigFile) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *ConfigFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ConfigFile) GetMtimeUnix() int64 {
	if x != nil {
		return x.MtimeUnix
	}
	return 0
}

func (x *ConfigFile) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

type DiscoverReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Files []*ConfigFile          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// 发现到的 server_name 列表（粗粒度），便于 UI 按站点呈现
	ServerNames   []string `protobuf:"bytes,2,rep,name=server_names,json=serverNames,proto3" json:"server_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverReply) Reset() {
	*x = DiscoverReply{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverReply) ProtoMessage() {}

func (x *DiscoverReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverReply.ProtoReflect.Descriptor instead.
func (*DiscoverReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoverReply) GetFiles() []*ConfigFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DiscoverReply) GetServerNames() []string {
	if x != nil {
		return x.ServerNames
	}
	return nil
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

type ListConfigsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ConfigFile          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsReply) Reset() {
	*x = ListConfigsReply{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsReply) ProtoMessage() {}

func (x *ListConfigsReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsReply.ProtoReflect.Descriptor instead.
func (*ListConfigsReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListConfigsReply) GetFiles() []*ConfigFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ReadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadConfigRequest) Reset() {
	*x = ReadConfigRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigRequest) ProtoMessage() {}

func (x *ReadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReadConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ReadConfigRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

type ReadConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadConfigReply) Reset() {
	*x = ReadConfigReply{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigReply) ProtoMessage() {}

func (x *ReadConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigReply.ProtoReflect.Descriptor instead.
func (*ReadConfigReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReadConfigReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadConfigReply) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type WriteConfigRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"` // 逻辑路径，由 Agent 映射到本地实际路径
	Content     []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // 回写后的配置文本
	Actor       string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`                                // 操作人（用于本地快照备注）
	AutoBackup  bool                   `protobuf:"varint,4,opt,name=auto_backup,json=autoBackup,proto3" json:"auto_backup,omitempty"`   // 写入前自动快照
	// 乐观锁：若非空，仅当目标文件当前 checksum 等于该值时才写入
	ExpectedChecksum string `protobuf:"bytes,5,opt,name=expected_checksum,json=expectedChecksum,proto3" json:"expected_checksum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteConfigRequest) Reset() {
	*x = WriteConfigRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigRequest) ProtoMessage() {}

func (x *WriteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigRequest.ProtoReflect.Descriptor instead.
func (*WriteConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *WriteConfigRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *WriteConfigRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteConfigRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *WriteConfigRequest) GetAutoBackup() bool {
	if x != nil {
		return x.AutoBackup
	}
	return false
}

func (x *WriteConfigRequest) GetExpectedChecksum() string {
	if x != nil {
		return x.ExpectedChecksum
	}
	return ""
}

type WriteConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BackupRef     string                 `protobuf:"bytes,2,opt,name=backup_ref,json=backupRef,proto3" json:"backup_ref,omitempty"` // 本次写入前的快照引用
	NewChecksum   string                 `protobuf:"bytes,3,opt,name=new_checksum,json=newChecksum,proto3" json:"new_checksum,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigReply) Reset() {
	*x = WriteConfigReply{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigReply) ProtoMessage() {}

func (x *WriteConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigReply.ProtoReflect.Descriptor instead.
func (*WriteConfigReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *WriteConfigReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WriteConfigReply) GetBackupRef() string {
	if x != nil {
		return x.BackupRef
	}
	return ""
}

func (x *WriteConfigReply) GetNewChecksum() string {
	if x != nil {
		return x.NewChecksum
	}
	return ""
}

func (x *WriteConfigReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	AutoBackup    bool                   `protobuf:"varint,3,opt,name=auto_backup,json=autoBackup,proto3" json:"auto_backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteConfigRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *DeleteConfigRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *DeleteConfigRequest) GetAutoBackup() bool {
	if x != nil {
		return x.AutoBackup
	}
	return false
}

type DeleteConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BackupRef     string                 `protobuf:"bytes,2,opt,name=backup_ref,json=backupRef,proto3" json:"backup_ref,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigReply) Reset() {
	*x = DeleteConfigReply{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigReply) ProtoMessage() {}

func (x *DeleteConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigReply.ProtoReflect.Descriptor instead.
func (*DeleteConfigReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteConfigReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteConfigReply) GetBackupRef() string {
	if x != nil {
		return x.BackupRef
	}
	return ""
}

func (x *DeleteConfigReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConfigRequest) Reset() {
	*x = TestConfigRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfigRequest) ProtoMessage() {}

func (x *TestConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfigRequest.ProtoReflect.Descriptor instead.
func (*TestConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

type TestConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // nginx -t 原始输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConfigReply) Reset() {
	*x = TestConfigReply{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfigReply) ProtoMessage() {}

func (x *TestConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfigReply.ProtoReflect.Descriptor instead.
func (*TestConfigReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *TestConfigReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestConfigReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

type ReloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadReply) Reset() {
	*x = ReloadReply{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadReply) ProtoMessage() {}

func (x *ReloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadReply.ProtoReflect.Descriptor instead.
func (*ReloadReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ReloadReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReloadReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type Backup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupRef     string                 `protobuf:"bytes,1,opt,name=backup_ref,json=backupRef,proto3" json:"backup_ref,omitempty"`
	LogicalPath   string                 `protobuf:"bytes,2,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Backup) GetBackupRef() string {
	if x != nil {
		return x.BackupRef
	}
	return ""
}

func (x *Backup) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *Backup) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Backup) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Backup) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"` // 可空，空则列全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ListBackupsRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

type ListBackupsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*Backup              `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsReply) Reset() {
	*x = ListBackupsReply{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsReply) ProtoMessage() {}

func (x *ListBackupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsReply.ProtoReflect.Descriptor instead.
func (*ListBackupsReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ListBackupsReply) GetBackups() []*Backup {
	if x != nil {
		return x.Backups
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupRef     string                 `protobuf:"bytes,1,opt,name=backup_ref,json=backupRef,proto3" json:"backup_ref,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *RollbackRequest) GetBackupRef() string {
	if x != nil {
		return x.BackupRef
	}
	return ""
}

func (x *RollbackRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type RollbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // nginx -t 输出
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackReply) Reset() {
	*x = RollbackReply{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReply) ProtoMessage() {}

func (x *RollbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReply.ProtoReflect.Descriptor instead.
func (*RollbackReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RollbackReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RollbackReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RollbackReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAgentSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentSettingsRequest) Reset() {
	*x = GetAgentSettingsRequest{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentSettingsRequest) ProtoMessage() {}

func (x *GetAgentSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentSettingsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

type UpdateAgentSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 快照保留份数（>0 时生效）
	BackupRetain int32 `protobuf:"varint,1,opt,name=backup_retain,json=backupRetain,proto3" json:"backup_retain,omitempty"`
	// 是否允许编辑主配置（仅当 agent 本地总闸 allow_main_config_remote=true 时可被远程开启）
	AllowMainConfig bool `protobuf:"varint,2,opt,name=allow_main_config,json=allowMainConfig,proto3" json:"allow_main_config,omitempty"`
	// 操作人（审计用）
	Actor         string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentSettingsRequest) Reset() {
	*x = UpdateAgentSettingsRequest{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentSettingsRequest) ProtoMessage() {}

func (x *UpdateAgentSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentSettingsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateAgentSettingsRequest) GetBackupRetain() int32 {
	if x != nil {
		return x.BackupRetain
	}
	return 0
}

func (x *UpdateAgentSettingsRequest) GetAllowMainConfig() bool {
	if x != nil {
		return x.AllowMainConfig
	}
	return false
}

func (x *UpdateAgentSettingsRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type AgentSettingsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackupRetain    int32                  `protobuf:"varint,1,opt,name=backup_retain,json=backupRetain,proto3" json:"backup_retain,omitempty"`
	AllowMainConfig bool                   `protobuf:"varint,2,opt,name=allow_main_config,json=allowMainConfig,proto3" json:"allow_main_config,omitempty"`
	// 本地总闸是否允许远程修改主配置开关；false 时 allow_main_config 不可被远程置 true
	AllowMainConfigRemote bool `protobuf:"varint,3,opt,name=allow_main_config_remote,json=allowMainConfigRemote,proto3" json:"allow_main_config_remote,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentSettingsReply) Reset() {
	*x = AgentSettingsReply{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSettingsReply) ProtoMessage() {}

func (x *AgentSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSettingsReply.ProtoReflect.Descriptor instead.
func (*AgentSettingsReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *AgentSettingsReply) GetBackupRetain() int32 {
	if x != nil {
		return x.BackupRetain
	}
	return 0
}

func (x *AgentSettingsReply) GetAllowMainConfig() bool {
	if x != nil {
		return x.AllowMainConfig
	}
	return false
}

func (x *AgentSettingsReply) GetAllowMainConfigRemote() bool {
	if x != nil {
		return x.AllowMainConfigRemote
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\rnginxadmin.v1\"\r\n" +
	"\vPingRequest\"Z\n" +
	"\tPingReply\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12(\n" +
	"\x10server_time_unix\x18\x02 \x01(\x03R\x0eserverTimeUnix\"\x0f\n" +
	"\rStatusRequest\"\xe3\x01\n" +
	"\vStatusReply\x12#\n" +
	"\rnginx_running\x18\x01 \x01(\bR\fnginxRunning\x12#\n" +
	"\rnginx_version\x18\x02 \x01(\tR\fnginxVersion\x12\x1d\n" +
	"\n" +
	"master_pid\x18\x03 \x01(\x05R\tmasterPid\x12\x1f\n" +
	"\vconfig_root\x18\x04 \x01(\tR\n" +
	"configRoot\x12 \n" +
	"\flast_test_ok\x18\x05 \x01(\bR\n" +
	"lastTestOk\x12(\n" +
	"\x10last_test_output\x18\x06 \x01(\tR\x0elastTestOutput\"~\n" +
	"\n" +
	"ConfigFile\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"mtime_unix\x18\x03 \x01(\x03R\tmtimeUnix\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\x11\n" +
	"\x0fDiscoverRequest\"c\n" +
	"\rDiscoverReply\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.nginxadmin.v1.ConfigFileR\x05files\x12!\n" +
	"\fserver_names\x18\x02 \x03(\tR\vserverNames\"\x14\n" +
	"\x12ListConfigsRequest\"C\n" +
	"\x10ListConfigsReply\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.nginxadmin.v1.ConfigFileR\x05files\"6\n" +
	"\x11ReadConfigRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\"G\n" +
	"\x0fReadConfigReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"\xb5\x01\n" +
	"\x12WriteConfigRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x1f\n" +
	"\vauto_backup\x18\x04 \x01(\bR\n" +
	"autoBackup\x12+\n" +
	"\x11expected_checksum\x18\x05 \x01(\tR\x10expectedChecksum\"z\n" +
	"\x10WriteConfigReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"backup_ref\x18\x02 \x01(\tR\tbackupRef\x12!\n" +
	"\fnew_checksum\x18\x03 \x01(\tR\vnewChecksum\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"o\n" +
	"\x13DeleteConfigRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x1f\n" +
	"\vauto_backup\x18\x03 \x01(\bR\n" +
	"autoBackup\"X\n" +
	"\x11DeleteConfigReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"backup_ref\x18\x02 \x01(\tR\tbackupRef\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x13\n" +
	"\x11TestConfigRequest\"9\n" +
	"\x0fTestConfigReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\x0f\n" +
	"\rReloadRequest\"5\n" +
	"\vReloadReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\xa2\x01\n" +
	"\x06Backup\x12\x1d\n" +
	"\n" +
	"backup_ref\x18\x01 \x01(\tR\tbackupRef\x12!\n" +
	"\flogical_path\x18\x02 \x01(\tR\vlogicalPath\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"7\n" +
	"\x12ListBackupsRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\"C\n" +
	"\x10ListBackupsReply\x12/\n" +
	"\abackups\x18\x01 \x03(\v2\x15.nginxadmin.v1.BackupR\abackups\"F\n" +
	"\x0fRollbackRequest\x12\x1d\n" +
	"\n" +
	"backup_ref\x18\x01 \x01(\tR\tbackupRef\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\"M\n" +
	"\rRollbackReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x19\n" +
	"\x17GetAgentSettingsRequest\"\x83\x01\n" +
	"\x1aUpdateAgentSettingsRequest\x12#\n" +
	"\rbackup_retain\x18\x01 \x01(\x05R\fbackupRetain\x12*\n" +
	"\x11allow_main_config\x18\x02 \x01(\bR\x0fallowMainConfig\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\"\x9e\x01\n" +
	"\x12AgentSettingsReply\x12#\n" +
	"\rbackup_retain\x18\x01 \x01(\x05R\fbackupRetain\x12*\n" +
	"\x11allow_main_config\x18\x02 \x01(\bR\x0fallowMainConfig\x127\n" +
	"\x18allow_main_config_remote\x18\x03 \x01(\bR\x15allowMainConfigRemote2\xa5\b\n" +
	"\fAgentService\x12<\n" +
	"\x04Ping\x12\x1a.nginxadmin.v1.PingRequest\x1a\x18.nginxadmin.v1.PingReply\x12E\n" +
	"\tGetStatus\x12\x1c.nginxadmin.v1.StatusRequest\x1a\x1a.nginxadmin.v1.StatusReply\x12O\n" +
	"\x0fDiscoverConfigs\x12\x1e.nginxadmin.v1.DiscoverRequest\x1a\x1c.nginxadmin.v1.DiscoverReply\x12Q\n" +
	"\vListConfigs\x12!.nginxadmin.v1.ListConfigsRequest\x1a\x1f.nginxadmin.v1.ListConfigsReply\x12N\n" +
	"\n" +
	"ReadConfig\x12 .nginxadmin.v1.ReadConfigRequest\x1a\x1e.nginxadmin.v1.ReadConfigReply\x12Q\n" +
	"\vWriteConfig\x12!.nginxadmin.v1.WriteConfigRequest\x1a\x1f.nginxadmin.v1.WriteConfigReply\x12T\n" +
	"\fDeleteConfig\x12\".nginxadmin.v1.DeleteConfigRequest\x1a .nginxadmin.v1.DeleteConfigReply\x12N\n" +
	"\n" +
	"TestConfig\x12 .nginxadmin.v1.TestConfigRequest\x1a\x1e.nginxadmin.v1.TestConfigReply\x12B\n" +
	"\x06Reload\x12\x1c.nginxadmin.v1.ReloadRequest\x1a\x1a.nginxadmin.v1.ReloadReply\x12Q\n" +
	"\vListBackups\x12!.nginxadmin.v1.ListBackupsRequest\x1a\x1f.nginxadmin.v1.ListBackupsReply\x12H\n" +
	"\bRollback\x12\x1e.nginxadmin.v1.RollbackRequest\x1a\x1c.nginxadmin.v1.RollbackReply\x12]\n" +
	"\x10GetAgentSettings\x12&.nginxadmin.v1.GetAgentSettingsRequest\x1a!.nginxadmin.v1.AgentSettingsReply\x12c\n" +
	"\x13UpdateAgentSettings\x12).nginxadmin.v1.UpdateAgentSettingsRequest\x1a!.nginxadmin.v1.AgentSettingsReplyB\x1cZ\x1anginx-agent/internal/pb;pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []any{
	(*PingRequest)(nil),                // 0: nginxadmin.v1.PingRequest
	(*PingReply)(nil),                  // 1: nginxadmin.v1.PingReply
	(*StatusRequest)(nil),              // 2: nginxadmin.v1.StatusRequest
	(*StatusReply)(nil),                // 3: nginxadmin.v1.StatusReply
	(*ConfigFile)(nil),                 // 4: nginxadmin.v1.ConfigFile
	(*DiscoverRequest)(nil),            // 5: nginxadmin.v1.DiscoverRequest
	(*DiscoverReply)(nil),              // 6: nginxadmin.v1.DiscoverReply
	(*ListConfigsRequest)(nil),         // 7: nginxadmin.v1.ListConfigsRequest
	(*ListConfigsReply)(nil),           // 8: nginxadmin.v1.ListConfigsReply
	(*ReadConfigRequest)(nil),          // 9: nginxadmin.v1.ReadConfigRequest
	(*ReadConfigReply)(nil),            // 10: nginxadmin.v1.ReadConfigReply
	(*WriteConfigRequest)(nil),         // 11: nginxadmin.v1.WriteConfigRequest
	(*WriteConfigReply)(nil),           // 12: nginxadmin.v1.WriteConfigReply
	(*DeleteConfigRequest)(nil),        // 13: nginxadmin.v1.DeleteConfigRequest
	(*DeleteConfigReply)(nil),          // 14: nginxadmin.v1.DeleteConfigReply
	(*TestConfigRequest)(nil),          // 15: nginxadmin.v1.TestConfigRequest
	(*TestConfigReply)(nil),            // 16: nginxadmin.v1.TestConfigReply
	(*ReloadRequest)(nil),              // 17: nginxadmin.v1.ReloadRequest
	(*ReloadReply)(nil),                // 18: nginxadmin.v1.ReloadReply
	(*Backup)(nil),                     // 19: nginxadmin.v1.Backup
	(*ListBackupsRequest)(nil),         // 20: nginxadmin.v1.ListBackupsRequest
	(*ListBackupsReply)(nil),           // 21: nginxadmin.v1.ListBackupsReply
	(*RollbackRequest)(nil),            // 22: nginxadmin.v1.RollbackRequest
	(*RollbackReply)(nil),              // 23: nginxadmin.v1.RollbackReply
	(*GetAgentSettingsRequest)(nil),    // 24: nginxadmin.v1.GetAgentSettingsRequest
	(*UpdateAgentSettingsRequest)(nil), // 25: nginxadmin.v1.UpdateAgentSettingsRequest
	(*AgentSettingsReply)(nil),         // 26: nginxadmin.v1.AgentSettingsReply
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: nginxadmin.v1.DiscoverReply.files:type_name -> nginxadmin.v1.ConfigFile
	4,  // 1: nginxadmin.v1.ListConfigsReply.files:type_name -> nginxadmin.v1.ConfigFile
	19, // 2: nginxadmin.v1.ListBackupsReply.backups:type_name -> nginxadmin.v1.Backup
	0,  // 3: nginxadmin.v1.AgentService.Ping:input_type -> nginxadmin.v1.PingRequest
	2,  // 4: nginxadmin.v1.AgentService.GetStatus:input_type -> nginxadmin.v1.StatusRequest
	5,  // 5: nginxadmin.v1.AgentService.DiscoverConfigs:input_type -> nginxadmin.v1.DiscoverRequest
	7,  // 6: nginxadmin.v1.AgentService.ListConfigs:input_type -> nginxadmin.v1.ListConfigsRequest
	9,  // 7: nginxadmin.v1.AgentService.ReadConfig:input_type -> nginxadmin.v1.ReadConfigRequest
	11, // 8: nginxadmin.v1.AgentService.WriteConfig:input_type -> nginxadmin.v1.WriteConfigRequest
	13, // 9: nginxadmin.v1.AgentService.DeleteConfig:input_type -> nginxadmin.v1.DeleteConfigRequest
	15, // 10: nginxadmin.v1.AgentService.TestConfig:input_type -> nginxadmin.v1.TestConfigRequest
	17, // 11: nginxadmin.v1.AgentService.Reload:input_type -> nginxadmin.v1.ReloadRequest
	20, // 12: nginxadmin.v1.AgentService.ListBackups:input_type -> nginxadmin.v1.ListBackupsRequest
	22, // 13: nginxadmin.v1.AgentService.Rollback:input_type -> nginxadmin.v1.RollbackRequest
	24, // 14: nginxadmin.v1.AgentService.GetAgentSettings:input_type -> nginxadmin.v1.GetAgentSettingsRequest
	25, // 15: nginxadmin.v1.AgentService.UpdateAgentSettings:input_type -> nginxadmin.v1.UpdateAgentSettingsRequest
	1,  // 16: nginxadmin.v1.AgentService.Ping:output_type -> nginxadmin.v1.PingReply
	3,  // 17: nginxadmin.v1.AgentService.GetStatus:output_type -> nginxadmin.v1.StatusReply
	6,  // 18: nginxadmin.v1.AgentService.DiscoverConfigs:output_type -> nginxadmin.v1.DiscoverReply
	8,  // 19: nginxadmin.v1.AgentService.ListConfigs:output_type -> nginxadmin.v1.ListConfigsReply
	10, // 20: nginxadmin.v1.AgentService.ReadConfig:output_type -> nginxadmin.v1.ReadConfigReply
	12, // 21: nginxadmin.v1.AgentService.WriteConfig:output_type -> nginxadmin.v1.WriteConfigReply
	14, // 22: nginxadmin.v1.AgentService.DeleteConfig:output_type -> nginxadmin.v1.DeleteConfigReply
	16, // 23: nginxadmin.v1.AgentService.TestConfig:output_type -> nginxadmin.v1.TestConfigReply
	18, // 24: nginxadmin.v1.AgentService.Reload:output_type -> nginxadmin.v1.ReloadReply
	21, // 25: nginxadmin.v1.AgentService.ListBackups:output_type -> nginxadmin.v1.ListBackupsReply
	23, // 26: nginxadmin.v1.AgentService.Rollback:output_type -> nginxadmin.v1.RollbackReply
	26, // 27: nginxadmin.v1.AgentService.GetAgentSettings:output_type -> nginxadmin.v1.AgentSettingsReply
	26, // 28: nginxadmin.v1.AgentService.UpdateAgentSettings:output_type -> nginxadmin.v1.AgentSettingsReply
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
